Ht5
Kistus/.net_coherent pull request #14
Opened 2024-11-07 22:48 UTC by Kistus

2024-11-12 13:16 UTC, IgorKheidorov requested changes
please fix comments

2024-11-12 13:16 UTC, IgorKheidorov commented on SparseMatrix.cs
> +    {
1. When implementing the GetCount(x) method, be aware that the argument value can be 0
2. Use LINQ here

2024-11-12 13:16 UTC, IgorKheidorov commented on Book.cs
> +                throw new ArgumentException("Title cannot be null or empty.", nameof(title));
1. move regexp to a const value, not to  create string any time
2. more reliable and effective to normalize isbn here and store it in normalized form

2024-11-24 22:47 UTC, Kistus commented
firts two commits to check

2024-11-25 07:54 UTC, IgorKheidorov approved these changes
Ok

2025-02-10 15:40 UTC, merged